-- 1. Players Table
create table players (
  id bigint generated by default as identity primary key,
  name text not null,
  team text not null,
  position text not null,
  college text not null,
  image_url text,
  tier int not null check (tier in (1, 2, 3)),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Rooms Table
create table rooms (
  id uuid default gen_random_uuid() primary key,
  code text not null unique,
  status text not null default 'WAITING' check (status in ('WAITING', 'PLAYING', 'FINISHED')),
  current_round int default 0,
  current_player_id bigint references players(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Participants Table
create table participants (
  id uuid default gen_random_uuid() primary key,
  room_id uuid references rooms(id) on delete cascade not null,
  username text not null,
  score int default 0,
  is_host boolean default false,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(room_id, username)
);

-- 4. Enable Realtime
alter publication supabase_realtime add table rooms;
alter publication supabase_realtime add table participants;

-- 5. RLS Policies (Public for now)
alter table players enable row level security;
create policy "Public read players" on players for select using (true);

alter table rooms enable row level security;
create policy "Public access rooms" on rooms for all using (true);

alter table participants enable row level security;
create policy "Public access participants" on participants for all using (true);